spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  thymeleaf:
    cache: false
  datasource:
    name: oauth_center
    url: jdbc:mysql://localhost:3306/oauth_center
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    defaultAutoCommit: false
security:
  oauth2:
    resource:
      service-id: client
mybatis:
  mapper-locations: classpath*:com/shine/web/mapper/*.xml
  type-aliases-package: com.shine.web.mapper
mapper:
  not-empty: false
  identity: MYSQL
  style: camelhumpAndLowercase
pagehelper:
  autoDialect: true
  closeConn: ture
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
